### ISSUE TITLE
Allow filtering and field selection on roles endpoint

### ISSUE THREAD

**Issue by eberleant** [Youtaite-Network/youtaite-network-api#33]
### Related
- [x] Blocks youtaite-network/youtaite-network-client#51

### Tasks
- [x] person_id query parameter filters results to only include roles with the given person id
- [x] collab_id query parameter filters results to only include roles with the given collab id
- [x] fields query parameter selects the fields to return
   - comma-separated list of fields
   - default value: `person_id,collab_id,role`
   - allowed fields: id, person_id, collab_id, role, created_at, updated_at
